project:
  type: website

website:
  title: "Test Site for a Quarto website"
  navbar:
    background: primary
    search: true
    right:
      - text: Home
        file: index.qmd
      - about.qmd
      - sidebar:Data
            
  sidebar: 
    - id: Data
      title: "Data"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - text: Current Data
          href: currentdata.qmd
        - text: Past Data
          href: pastdata.qmd
          
  page-footer: 
    left: "Copyright 2023, Clara Peers" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/
    
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

